services:
    api:
        container_name: blog-server
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:17
        container_name: blog-db
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
